### ISSUE TITLE
Draggable - Pinch zoom issues after clicking "#" link 

### ISSUE THREAD

**Issue by nickff** [furf/jquery-ui-touch-punch#1]
Pinch zooming / double-tapping work great on page load, but when you click either the "projects" or "products" links (which both have an href of "#"), and THEN try pinching or double-tapping, my draggable box reacts to the pinch zooming and jump all over the screen.

http://future.thefutureforward.com/~steady/

Let me know your thoughts, and thanks for the amazing plugin!

**Comment by furf** [comment]
Please try the latest version. A major refactor seems to have resolved most other issues and may resolve yours. Let me know how it goes! Thanks for using.
