### ISSUE TITLE
Draggable in img

### ISSUE THREAD

**Issue by PauloAlmeida** [furf/jquery-ui-touch-punch#10]
I there it's seems to work perfectly into the ipad has long you assign it to a div but does not work when assign to a img, can you help me?

**Comment by PauloAlmeida** [comment]
I've realize that error in not in the fact that I'm trying to move images but because I create them programmatically and I cant seem to be able to bind the Draggable function so that it recognize the draggable objects

**Comment by furf** [comment]
It should work as long as you call draggable after the image is added to the DOM.
