### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by brommer** [furf/jquery-ui-touch-punch#107]
Hi there,

it would be great to have bower support. 

Regards

**Comment by seiyria** [comment]
+1

**Comment by wshaver** [comment]
+1

**Comment by stasberkov** [comment]
Please, introduce bower support

**Comment by garciav** [comment]
Really, please. Bower support

**Comment by renaekathleen** [comment]
Yes please!

**Comment by furf** [comment]
Added. Now if anyone sees functino, tell him to unregister his fork from the proper name `jquery-ui-touch-punch` :smirk:

**Comment by furf** [comment]
Until then, `bower install jqueryui-touch-punch`.

**Comment by jleaders** [comment]
I still get @functino  errors (tested on Ubuntu 16.04)

```
$ bower install furf/jquery-ui-touch-punch
bower furf/jquery-ui-touch-punch=furf/jquery-ui-touch-punch#*          ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/functino/jquery-ui-touch-punch.git", exit code of #128 remote: Repository not found. fatal: Authentication failed for 'https://github.com/functino/jquery-ui-touch-punch.git/'

Additional error details:
remote: Repository not found.
```

**Comment by jleaders** [comment]
Other people are having this issue too: https://stackoverflow.com/questions/49155944/git-repository-bower-install-terminal-prompts-disabled

**Comment by jleaders** [comment]
Duplicate of #192

**Comment by functino** [comment]
Hi @jleaders,
doing `bower install furf/jquery-ui-touch-punch` should work just fine.
Up until now `bower install jquery-ui-touch-punch` did not work because I deleted my fork of this repo. I didn't remember that I registered this as a bower package. Sorry.

I've just unregistered `jquery-ui-touch-punch` so feel free to grab it.
//cc @furf

**Comment by jleaders** [comment]
@functino It works now, thank you.

**Comment by jleaders** [comment]
Oddly on one machine I had to do `bower install furf/jqueryui-touch-punch` [sic] (not sure why the dash was missing)
