### ISSUE TITLE
Not working on Samsung Galaxy Note 2 with Chrome

### ISSUE THREAD

**Issue by brunocramos** [furf/jquery-ui-touch-punch#108]
I've tried your examples on my Samsung Galaxy Note 2 with Chrome but all the drag and drop and resize examples don't work on my smartphone. I even tested on your own site with your examples. It simply does nothing.
Any clue about it?

**Comment by mikesir87** [comment]
Duplicate of Issue #99 - Chrome doesn't load the resource based on its MIME type sent from the GitHub server
