### ISSUE TITLE
Jquery >1.6 Slider issue

### ISSUE THREAD

**Issue by tarcon** [furf/jquery-ui-touch-punch#12]
Tapping anyhwere in the slider area should set a new value and move the handle. This does only work until the handle has been initially moved by dragging. After that tapping causes no reaction. The "change" event fires nevertheless, it does not set a new ui.value though. This is independent from the animate property.

Recreate:
1. Create a jquery ui slider and include the jquery-ui-touch-punch script
2. Control the slider once by dragging the handle
3. Tap next to the handle to control the slider by clicking

The phenomenon does not occur if jquery < 1.6 is used 
Tested on ipad 1/2 and ipad simulator

**Comment by furf** [comment]
Unable to reproduce. I tried with single value and multiple values. If you can provide a broken example, I will reopen the issue.
