### ISSUE TITLE
Dragging demo doesn't work on iPad/iPhone with jQuery 1.10.2

### ISSUE THREAD

**Issue by unlabeled** [furf/jquery-ui-touch-punch#127]
On Chrome and Safari at least. When I manually switch to jQuery 1.7.2 it works fine. Any idea?

**Comment by gianarb** [comment]
I have same problem

**Comment by jinyoungc** [comment]
It works with jQuery 1.9.1

**Comment by furf** [comment]
Incomplete issue. See http://touchpunch.furf.com/#issues 
Include full details. Version of jQuery, jQuery UI and preferably a page demonstrating the bug.

**Comment by furf** [comment]
Could not replicate. Works fine here using jQuery 1.10.2 (w/ jQueryUI 1.10.2). Need more specifics about your environment and possibly a demo. http://touchpunch.furf.com/#issues
