### ISSUE TITLE
Draggable / resizable demo doesn't work with desktop Chrome when touch events override turned on

### ISSUE THREAD

**Issue by asavin** [furf/jquery-ui-touch-punch#128]
When trying demos on desktop Chrome with touch events override enabled, draggable and resizable demos doesn't work. Selectable works nice, sortable again doesn't work since it requires dragging the element.

This might be related to the following warning I'm getting in the Chrome console:

```
Refused to execute script from 'https://raw.github.com/furf/jquery-ui-touch-punch/master/jquery.ui.touch-punch.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```

**Comment by mohitharrak** [comment]
i am seeing the same issue too

**Comment by mohitharrak** [comment]
https://github.com/furf/jquery-ui-touch-punch/issues/99

**Comment by upendrawatwe** [comment]
I tried the solution by steve fenton.@ www.stevefenton.com .interested folk
could use this alternative..I made use of this for my application - working
sample exists on www.aadityaglobal.com/magboard/test-taptap4.htm
