### ISSUE TITLE
disable sortable

### ISSUE THREAD

**Issue by shhstudios** [furf/jquery-ui-touch-punch#13]
Thanks for the great plugin!

I'm trying to toggle enable/disable sortable. 

$('ul').sortable( "disable" );

This works well on on the browser but not on iPhone/simulator. Is there any other way to do this?

Thank you!

**Comment by pixelass** [comment]
Same request.
disable seems to work "sometimes" but very often it does not work for mobile touch (iPhone 4 iOS5).
The last dragged (sortable) item remains draggable even after disabling. (others seem to be fixed)

I haven't found a source to this problem yet, but it seems to happen at specific occasions.

**Comment by pixelass** [comment]
here's an example:
http://css.pixelass.com/iphone
it's a recreation of iOS5 as a webapp.. so save it to your homescreen to test it.

Doubletap anywhere (really fast) to enable sorting (wiggle).
You can even move items from the dock to the homescreen and the Dock can only hold 4 icons. Everything seems to work fine. 
Doubletap again to disable sorting and wiggle. Sometimes one icon (I think it's the one, that was in the place, where the last sorted icon now is) follows the movement of the finger (with the offset it had to the finger when the first touch occurred)

With sometimes I mean.. sometimes it happens during an edit (after enabling) sometimes it happens after the first disable... sometimes it happens after the 2nd or 3rd... disable.

If you click on the music icon it opens a new view. There are 3 elements that can also be sorted (without enable/disable). Everything seems to work as expected here.

The issue only occurs for touch events (I only tested iPhone4 iOS5).....
I tried disabling the slider (2nd Homescreen) but the bug still occurs even if I disable all other javascripts

I am using this to enable/disable sorting

<code> 
$("#launcherbox1, #launcherbox2, #dockbox").sortable('enable');
$("#launcherbox1, #launcherbox2, #dockbox").sortable('disable');
</code>

and this to define the connections and limit

<code> 
        $("#launcherbox1, #launcherbox2, #dockbox").sortable({
            connectWith: '.droppable',
            receive: function(event, ui) {
                if ($('#dockbox').children().length > 4) {
                    $(ui.sender).sortable('cancel');

```
            }
        }
    });
```

</code>
I hope that helps a little to recreate the problem.

_________---UPDATE---____________

After more testing, it seems, that the disabling does not work at all for containers that were sorted. Unsorted containers are not affected. After DISABLE when you "swipe" over the container where elements were sorted the last sorted element moves with the touch.

**Comment by furf** [comment]
Latest version should address this issue. Please test and LMK.

**Comment by pixelass** [comment]
I tested it and can confirm that it doesn't cause this issue anymore.
First test have been completed with good results.
