### ISSUE TITLE
ENH: Create a gh_pages branch

### ISSUE THREAD

**Issue by westurner** [furf/jquery-ui-touch-punch#135]
Serving JS from raw.github is discouraged; and doesn't work on Chrome for Android (#119):

Solution: serve JS from GitHub Pages:
- http://pages.github.com/
- create a `gh_pages` branch
- create a build script (`.sh`, `Makefile`, `gruntfile`, `.py`, ...). Either:
  - manually copy the latest versions from `master` the `gh_pages` branch OR
  - OR just `ghp-import .` (https://github.com/davisp/ghp-import)

**Comment by furf** [comment]
Thanks for the suggestion. I will consider it. For now, the demos are using touch punch loaded from cdnjs. This is a short term fix until the next release. Cheers!

**Comment by westurner** [comment]
Cool. Thanks!
