### ISSUE TITLE
Html5 Drag drop not working in iPad

### ISSUE THREAD

**Issue by sendtoharmeet** [furf/jquery-ui-touch-punch#136]
Hi,

How can i run my html5 drag drop application in ipad.

http://www.w3schools.com/html/html5_draganddrop.asp

Above example is not working on iPad. Please help me.

Regards,
Harmeet

**Comment by furf** [comment]
jQuery UI Touch Punch only implements touch events in jQuery UI. It is not an all-purpose touch events library. The page you are referencing is a demo of native HTML5 drag-and-drop.
