### ISSUE TITLE
Uncaught error: 

### ISSUE THREAD

**Issue by Latchumi** [furf/jquery-ui-touch-punch#138]
Hi,

Through the following error: 
      Uncaught TypeError: Cannot read property 'mouse' of undefined 
where $.ui.mouse is used

![screenshot 12](https://f.cloud.github.com/assets/3919908/1954165/667b1068-81d0-11e3-8321-4e708526e0a9.png)

**Comment by shuckster** [comment]
Which versions of jQuery and jQuery UI are you using?

**Comment by furf** [comment]
Cannot read property 'mouse' of undefined means jQuery.UI is not defined. This means either you are not using jQuery UI and this is the wrong library for you. Or you have included the scripts in the wrong order. See: http://touchpunch.furf.com/#usage
