### ISSUE TITLE
Doesn't work on Nexus 5 (4.4.2) with Chrome (32.0.1700.99)

### ISSUE THREAD

**Issue by noVerity** [furf/jquery-ui-touch-punch#139]
I tried to implement it in my project without it working and then checked back on http://touchpunch.furf.com/ and the examples there aren't working either.

**Comment by ghost** [comment]
I can confirm this with Nexus 5 with 4.4.2 with same Chrome build.

**Comment by Makkurokurosuke** [comment]
I got the same problem with Nexus 5 (Android 4.4.0 Chrome 32.0).

I saved the demo page and opened it as a local file on Chrome.
When I changed
from script src="https://raw.github.com/furf/jquery-ui-touch-punch/master/jquery.ui.touch-punch.min.js"
to script src="jquery.ui.touch-punch.min.js"
 (exactly the same source code), it worked fine. but when the link is the absolute path, it didn't work. I am not sure if this solves your problem. I didn't test it against web server.

**Comment by peturh** [comment]
@Makkurokurosuke: Thanks! That worked for me to, but I'd say that's a very strange behavior.

**Comment by furf** [comment]
raw.github.com serves JavaScript as text/plain which will not run in stricter browsers. that is the fail. I have noted my mistake and updated the pointer.

**Do not hotlink to Github.** Instead, download the script and serve it from your personal server. Consider making it part of your build process to concatenate it into your script bundle. Or load from a CDN like: http://cdnjs.com/libraries/jqueryui-touch-punch/

**Comment by omipandey** [comment]
@furf  , u are again referencing a issue to one that is also unsolved ... please provide solution instead of running away from it .
