### ISSUE TITLE
multiple sliders

### ISSUE THREAD

**Issue by bruzed** [furf/jquery-ui-touch-punch#15]
when clicking and dragging one slider both sliders move at the same time. they also get stuck.

**Comment by ghost** [comment]
Was this issue ever resolved? currently having a major issue with this, using a vertical and horizontal slider on a single page. Tried using several versions (including forks from main) but issue is still present.

**Comment by bruzed** [comment]
nope i didn't try to fix it, used http://code.google.com/p/jquery-ui-for-ipad-and-iphone/ instead.

**Comment by ghost** [comment]
@bruzed: I tried out that version previously but couldn't find how to use it properly, there is no documentation. All I did was load the JS library (jquery-ui-for-ipad-and-iphone) and call this on a slider: $('#slider').dialog().addTouch(); ... but it didn't work. Would you mind telling me what code you used to get multiple sliders working?

**Comment by bruzed** [comment]
sure here's a little example i put together: https://github.com/bruzed/jquery_ui_touch_slider

**Comment by ghost** [comment]
Awesome! I had no idea you had to append the .addTouch(); to the .slider() function initialiser itself. This has been of much help! Thanks a lot.

**Comment by furf** [comment]
Apologies for my unresponsiveness — it's been a very busy few months. Can you tell me the jquery and jquery-ui version numbers you were working with? I am not able to reproduce this bug. If you have source examples, they would be greatly appreciated.

**Comment by furf** [comment]
I've been playing with this one for a while and cannot reproduce. If you can provide a broken example, I will reopen and investigate. Thanks.
