### ISSUE TITLE
Drag two items separately at the same time?

### ISSUE THREAD

**Issue by igormakovsky** [furf/jquery-ui-touch-punch#163]
Is it possible to drag two items separately at the same time on any mobile device? By default it isn't allowed. Some other known scripts allow it, but I'd prefer using only Jquery UI. Thanks in advance.

**Comment by furf** [comment]
This lib was only intended as a temporary fill for the missing touch in jQuery UI, which itself does not support simultaneous events. Multiple events is currently out of scope of this project, but I may consider it in the future as an interesting code challenge.
