### ISSUE TITLE
add bower

### ISSUE THREAD

**Issue by gbelmm** [furf/jquery-ui-touch-punch#192]
add bower please

**Comment by PabloVallejo** [comment]
:+1:  Having this project as a bower package would be very helpful!

**Comment by SlyDeath** [comment]
Если его там нет, как я его вчера через bower установил? Оо

**Comment by PabloVallejo** [comment]
The library can be used in bower referencing the `master` branch.

``` json
"jqueryui-touch-punch": "master"
```

Nevertheless it'd be nice to have it versioned so that we can use it like for example:

``` json
"jqueryui-touch-punch": "1.0.0"
```

**Comment by SlyDeath** [comment]
```
"jqueryui-touch-punch": "*"
```

also work

**Comment by PabloVallejo** [comment]
:+1:

**Comment by kiangtengl** [comment]
@PabloVallejo How did you get it to work? Did you do:

`bower install jqueryui-touch-punch`

Or did you download and include the package manually?

**Comment by PabloVallejo** [comment]
In my `bower.json` I added 

``` json
"jqueryui-touch-punch": "master"
```

and then issued `bower install`

Alternatively you can do so using

``` bash
bower install jqueryui-touch-punch --save
```

which adds `"jqueryui-touch-punch": "*"` to bower.json
see: http://bower.io/docs/api/#install

**Comment by furf** [comment]
Added. Now if anyone sees functino, tell him to unregister his fork from the proper name `jquery-ui-touch-punch` :smirk:

**Comment by furf** [comment]
Until then, `bower install jqueryui-touch-punch`.
