### ISSUE TITLE
301PermMove

### ISSUE THREAD

**Issue by desmeit** [furf/jquery-ui-touch-punch#193]
Hello,

sorry for this beginner question, but the script is not working to me.

<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.2.min.js"></script>

<script type="text/javascript" src="http://code.jquery.com/ui/1.8.21/jquery-ui.min.js"></script>

```
<script type="text/javascript" src="/scripts/slider/jquery.ui.touch-punch.min.js"></script>
```

UI Touch brings an 301PermMove Error. What I have to do?

Best regards

**Comment by furf** [comment]
That is a server configuration issue. Did you move the file?
