### ISSUE TITLE
What is the hit area for the sortable function?

### ISSUE THREAD

**Issue by chimmy** [furf/jquery-ui-touch-punch#197]
I'm using the sortable function with a grid of float left LI. For the most part it works except when trying to drag an element to right most LI, which sometimes works sometimes doesn't.

I am assuming because its original intentions was that it work on a vertical system and that the the actions are a bit unintended to work in this manner.

My question is what determines when an LI shifts position?

thanks.

**Comment by furf** [comment]
This looks like a jQuery UI-specific issue. I am happy to help if you provide an example. My hunch is that adding `overflow:hidden` to the containing list would help.
