### ISSUE TITLE
Minified version wrong commenting

### ISSUE THREAD

**Issue by AlexRevin** [furf/jquery-ui-touch-punch#200]
Hello

Please fix the wrong comment ending in minified version:

```
 *  jquery.ui.widget.js
 *  jquery.ui.mouse.js
 */
!function(a){function f(a,b)
```

The exclamation sign breaks the whole thing

**Comment by furf** [comment]
The exclamation point is not the end of the comment. It is the beginning of the self-executing function statement below the comment. The code works for me. Please elaborate or show me an example where the functionality is broken.

**Comment by AlexRevin** [comment]
It gets broken when concatenating file into the packed library along with other libraries.
