### ISSUE TITLE
Elements change position when resizing

### ISSUE THREAD

**Issue by namrehcram** [furf/jquery-ui-touch-punch#201]
When I resize an element (dragging is okay), other (resizable and draggable) elements change position, compensating for the changed position of the resized element it seems. Once an element has been resized, that repositioning no longer occurs.
How to prevent that from happening in the first place?

**Comment by furf** [comment]
Is it possible that your element is not absolutely positioned? Please provide an example online for me to review.

**Comment by furf** [comment]
This seems to be a jQuery issue and not a Touch Punch issue. Closing for now.
