### ISSUE TITLE
README lacks sufficient humor

### ISSUE THREAD

**Issue by infinityplusone** [furf/jquery-ui-touch-punch#205]
Please: Bring the funny.

**Comment by furf** [comment]
Your mom's cunt brings the funny. And the :clap:.

**Comment by furf** [comment]
Yeah, that's right. I brought your mom into this like it was a swinger's club.

**Comment by furf** [comment]
But she's so old, she used to swing a club.

**Comment by furf** [comment]
('cause she's like prehistoric.)

**Comment by furf** [comment]
Daamn.
