### ISSUE TITLE
item "jumping" up on ipad

### ISSUE THREAD

**Issue by avoliva** [furf/jquery-ui-touch-punch#288]
When dragging, the dragged item sometimes jumps up from where the finger is, and it's about 2 inches above where my finger is. But the dragging still works it's just the item is out of sync I guess for whatever reason.

**Comment by MichaelHydra** [comment]
Having a similar issue but on Android devices and it only seems to happen on pages that have a vertical scroll. Any ideas what could be causing this?

**Comment by avoliva** [comment]
Sorry forgot about this, I was able to fix this with this on jquery ui
```javascript
helper: function(event, ui) {
    var $clone =  $(ui).clone();
    $clone .css('position','absolute');
    return $clone.get(0);
},
```
