### ISSUE TITLE
Button on draggable container ,click not working on Samsung S7

### ISSUE THREAD

**Issue by shubknit** [furf/jquery-ui-touch-punch#304]
Hi team,

I have one requirement as follows: 
I have a drag gable container which has  a button on it .
So when I used 
$('#myPrivacyPopUp').draggable({
            handle: '.modal-privacy-content'
 });
Button click stops working. It is not working on Samsung S7 mobile series. 
Works fine on IOS
Let me know , if there is some fix for this.

![image](https://user-images.githubusercontent.com/5492031/42927105-092384d8-8b51-11e8-9d50-267949666770.png)

**Comment by michaelchandrag** [comment]
Hello, Shubknit!
I have a very similar issues to yours.
However, my element is an a href and the parent is a div which has a draggable function.
The draggable function is working fine, but the onclick function doesn't work.
I haven't tried using iOS mobile, but on my Samsung S7 also didn't working as expected.
Hope to see any changes from you!

**Comment by shubknit** [comment]
Hi Michael,
I have no workaround to fix this. So we are going with the known issue on this device

Regards
Shubham
