### ISSUE TITLE
Can't click on the link in the li

### ISSUE THREAD

**Issue by thomasFoglia** [furf/jquery-ui-touch-punch#311]
on Android, i can't click on the link which is in the li like this :
```
<ul>
<li> <img src=''>LI 1</li>
<li> <img src=''>LI 2</li>
</ul>
```

the action onClick is on the onclick on the img.

thanks

**Comment by Raymond-Naseef** [comment]
Bad html - missing > before <img>

**Comment by thomasFoglia** [comment]
Thanks... But it's only a typing error 😎

**Comment by thomasFoglia** [comment]
Okay it's fixed in this thread !!!!
https://github.com/furf/jquery-ui-touch-punch/pull/109
