### ISSUE TITLE
Using different versions of jQuery and jQueryUI together

### ISSUE THREAD

**Issue by Sukumaran001** [furf/jquery-ui-touch-punch#332]
**I have worked the jQuery and jQuery UI with different version, I just using jQuery UI  drag the element in mobile view that normally works fine but they conflict issue ** 

 _jQuery version ->3.6.0_ `<script src="../resources/vendors/jquery/jquery-3.6.0.min.js"></script>`
_jQuery  UI version ->1.13.1_  `<script src="../resources/vendors/jquery/jquery_UI/jquery-ui.min.js"></script>`

 **they have conflict the jquery.min.js ** 
**error:** 
> [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example, because scrolling is in progress and cannot be interrupted.
> 
> [Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example, because scrolling is in progress and cannot be interrupted.
> 
> [Intervention] Ignored attempt to cancel a touchend event with cancelable=false, for example, because scrolling is in progress and cannot be interrupted.
> 

_How to Using different versions of jQuery and jQuery UI together?_

**Comment by RWAP** [comment]
No idea here - that looks like an issue with jQuery / jQuery UI not touch-punch.

**Comment by Sukumaran001** [comment]
@RWAP sir kindly check that. Not only jQuery/jQuery UI sir, that normally working on inspect element area in mobile view, but that error was occurred by real android device.

I'm using this cdn for touch punch-> `<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js" integrity="sha512-0bEtK0USNd96MnO4XhH8jhv3nyRF0eK87pJke6pkYf3cM0uDIhNJy9ltuzqgypoIFXw3JSuiy04tVk4AjpZdZw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>`

cdn link ->https://cdnjs.com/libraries/jqueryui-touch-punch

**Comment by Sukumaran001** [comment]
I've got a solution for this issue 

 update the version of touch-punch.

https://github.com/RWAP/jquery-ui-touch-punch 

Thanks for your supporting
