### ISSUE TITLE
Is this package still needed in 2023?

### ISSUE THREAD

**Issue by jaradc** [furf/jquery-ui-touch-punch#336]
I don't mean my question to sound derogatory, I'm legit asking. With the advancement of browser compatibility and perhaps recent upgrades of jQuery packages (jquery-ui?, jquery?), is jquery-ui-touch-punch still needed to handle touch events? I've had it in my project base for a long time, but honestly don't even know if it works or is still necessary. I use jquery and jquery-ui.

**Comment by RWAP** [comment]
Yes it is still required unfortunately - although this branch is long since defunct and unsupported, so you should be using the latest:

https://github.com/RWAP/jquery-ui-touch-punch

**Comment by jaradc** [comment]
Oh, got it. Good to know! Thanks so much. Didn't even realize that.
