### ISSUE TITLE
Drag not working on iPad Safari

### ISSUE THREAD

**Issue by ahmadassaf** [furf/jquery-ui-touch-punch#34]
Hello,

I have tried to used the library on the iPad, when testing on Dolphin browser the drag is enables, however on Safari it is not working. Nothing Happens.

Thanks

**Comment by coli** [comment]
Yeah, sortable is totally not working on ipad 3

**Comment by furf** [comment]
What versions of jQuery and jQuery UI are you using?

NOTE: jQuery UI 1.8 is incompatible with jQuery 1.8. Use jQuery 1.7.2 instead. This is not a touchpunch issue.

I am closing this bug as incomplete. Please provide a live example or jsFiddle and a better description of the error. The code is testing fine here. You might be doing something wrong but I have no way to tell.

**Comment by coli** [comment]
Try the sortable demo on the  front page on ipad 3 http://touchpunch.furf.com/

**Comment by coli** [comment]
Actually, non of the drag and drop demo are working at all there...

**Comment by furf** [comment]
Unfortunately I only have an iPhone 4S and iPad 2 for testing. Everything is working here. 

Maybe you can help by debugging the problem on your server and submitting a bug fix.

**Comment by coli** [comment]
Interesting, we'll probably spend some time debugging it when we get to iPad support for our product. Thanks!

**Comment by ahmadassaf** [comment]
Hello, sorry for the late reply, actually i have got it working under the iPad, for me the problem was adjusting the order of which i import the external JS libraries, i ad quite few on my project and importing the touchpunch JS file at the end made the trick

**Comment by MurukanK** [comment]
can it drag in touch phone?
