### ISSUE TITLE
'undefined' is not a function

### ISSUE THREAD

**Issue by umpirsky** [furf/jquery-ui-touch-punch#51]
I'm getting `'undefined' is not a function` error on iPad. I debugged it and found that it happens in line [#154](https://github.com/furf/jquery-ui-touch-punch/blob/master/jquery.ui.touch-punch.js#L154). Somehow `$.proxy` is undefined.

**Comment by furf** [comment]
Did you include jQuery on the page before touch punch?

**Comment by umpirsky** [comment]
Fixed by updating jQuery and jQueryUI to latest version.
