### ISSUE TITLE
Resizable gets "stuck"

### ISSUE THREAD

**Issue by kirb** [furf/jquery-ui-touch-punch#6]
To reproduce:
1. Go to a page with touch-punch and a resizable element on an iDevice
2. Drag the resize handle out quickly, so that your finger is outside of the element
3. Drag your finger anywhere around the screen. 
The element continues to be draggable, even when the handle isn't touched. 

I can have a look at the code and see if I can fix it if you want. 
Ad@m

**Comment by glennfu** [comment]
I took a look at this plugin to try it out and immediately ran into the same problem.  It happens on the demo page.

**Comment by glennfu** [comment]
At line 66 I put:

```
self._touchMoveDelegate = function (event) {
  if (self.started)
    return self._mouseMove(makeMouseEvent(event));
  else
    return true;
};
```

and then set started to true on touchstart and false at touchend, and that seems to have fixed this bug.  Overall it's still a bit buggy it seems.  Sometimes I have to tap on my anchor like 5 times before it works, and sometimes when I drag, the box jumps out a bit.  Not sure why that is yet, but at least this is one bug down.

**Comment by kirb** [comment]
I have forked the repo and added the above change to the script, which you can find here:

https://github.com/kirbylover4000/jquery-ui-touch-punch/

Ad@m

**Comment by furf** [comment]
Looking into some of resizable's issues... keep you posted.

**Comment by furf** [comment]
I handled the issue slightly differently and it seems to have fixed the stickiness and greatly improved the behavior of resizable. There is one remaining issue where after resizing, you can resize the element from "inside" the element. I will close this issue for now and open a separate one for that issue. Please take a look and let me know what you think. Thanks for the valuable feedback.
