### ISSUE TITLE
Sortable elements should (have the option) to only be dragged vertically or horizontally

### ISSUE THREAD

**Issue by gabriel-r** [furf/jquery-ui-touch-punch#82]
Sortable elements should (have the option) to only be dragged vertically or horizontally.

**Comment by EricMKaufman** [comment]
Gabriel,

This is an option of Sortable. Review the API:
http://api.jqueryui.com/sortable/#option-axis

**Comment by gabriel-r** [comment]
OMG, you rock! 
Thank you!
