### ISSUE TITLE
Spelling mistake in readme.md - becuase

### ISSUE THREAD

**Issue by davebobak** [furf/jquery-ui-touch-punch#87]
In readme.md
(https://github.com/furf/jquery-ui-touch-punch#touch-event-support-for-jquery-ui)

because is spelled "becuase"

...touch-enabled mobile devices, **becuase** jQuery UI listens to mouse events—mouseover, mousemove and mouseout—not touch events...

**Comment by fALKENdk** [comment]
Fixed here #92

**Comment by furf** [comment]
In case you hadn't watched:

https://www.youtube.com/watch?v=jutl36xdNbM#t=2201

You're a YouTube :star2:!
